package processing.test.projetgui;

import processing.core.*; 
import processing.data.*; 
import processing.event.*; 
import processing.opengl.*; 

import g4p_controls.*; 

import java.util.HashMap; 
import java.util.ArrayList; 
import java.io.File; 
import java.io.BufferedReader; 
import java.io.PrintWriter; 
import java.io.InputStream; 
import java.io.OutputStream; 
import java.io.IOException; 

public class ProjetGui extends PApplet {

// Need G4P library



public void setup(){
 
  createGUI();
  customGUI();
  // Place your setup code here
  
}

public void draw(){
  background(230);
  
}

// Use this method to add additional statements
// to customise the GUI controls
public void customGUI(){

}
/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:814843:
  println("textarea1 - GTextArea event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:textarea1:814843:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:376006:
  println("textfield1 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:textfield1:376006:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:667050:
  println("button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:button1:667050:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:916312:
  println("custom_slider1 - GCustomSlider event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:custom_slider1:916312:

public void stick1_change1(GStick source, GEvent event) { //_CODE_:stick1:799034:
  println("stick1 - GStick event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:stick1:799034:

public void knob1_turn1(GKnob source, GEvent event) { //_CODE_:knob1:430804:
  println("knob1 - GKnob event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:knob1:430804:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  textarea1 = new GTextArea(this, 17, 45, 160, 80, G4P.SCROLLBARS_NONE);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  textfield1 = new GTextField(this, 19, 8, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  button1 = new GButton(this, 195, 11, 80, 30);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click1");
  custom_slider1 = new GCustomSlider(this, 40, 159, 100, 40, "grey_blue");
  custom_slider1.setLimits(0.5f, 0.0f, 1.0f);
  custom_slider1.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
  stick1 = new GStick(this, 280, 208, 60, 60);
  stick1.setMode(G4P.X4);
  stick1.setOpaque(false);
  stick1.addEventHandler(this, "stick1_change1");
  knob1 = new GKnob(this, 268, 121, 60, 60, 0.8f);
  knob1.setTurnRange(110, 70);
  knob1.setTurnMode(GKnob.CTRL_HORIZONTAL);
  knob1.setSensitivity(1);
  knob1.setShowArcOnly(false);
  knob1.setOverArcOnly(false);
  knob1.setIncludeOverBezel(false);
  knob1.setShowTrack(true);
  knob1.setLimits(0.5f, 0.0f, 1.0f);
  knob1.setShowTicks(true);
  knob1.setOpaque(false);
  knob1.addEventHandler(this, "knob1_turn1");
}

// Variable declarations 
// autogenerated do not edit
GTextArea textarea1; 
GTextField textfield1; 
GButton button1; 
GCustomSlider custom_slider1; 
GStick stick1; 
GKnob knob1; 

  public int sketchWidth() { return 480; }
  public int sketchHeight() { return 320; }
  public String sketchRenderer() { return JAVA2D; }
}
